
services:
  db:
    image: postgres:15
    container_name: zap_db
    restart: always
    env_file:  
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}  
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}  
      - POSTGRES_DB=${POSTGRES_DB}  
    ports: 
      - "5432:5432"  
    volumes:
      - pg_data:/var/lib/postgresql/data  
    networks:
      - internal_network 

  
  app:
    build: .
    container_name: zap_app
    restart: always
    depends_on:
      - db
      - zap
    env_file:  
      - .env  
    ports:
      - "5000:5000" 
    networks:
      - internal_network


  zap:
    image: owasp/zap2docker-stable
    container_name: zap_proxy
    restart: always
    env_file:
      - .env  
    command: >
      sh -c "zap.sh -daemon -port 8080 -host 0.0.0.0 -config api.key=$${ZAP_API_KEY}"
    ports:
      - "8080:8080" 
    networks:
      - internal_network

volumes:
  pg_data:

networks:
  internal_network:
    driver: bridge